### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by cjbottaro** [esl/fusco#15]
Hello,

I'm looking for a simple HTTP client for use with interacting with an Etcd cluster.  I have the requirement that the library not be an OTP application.

Is this library near production ready?  Or can you recommend any other HTTP client that isn't an OTP app (e.g. you just need to call `start_link` to get a pid)?

Thank you.

**Comment by michalwski** [comment]
We successfully use this HTTP client with [esl/MongooseIM](https://github.com/esl/MongooseIM) on many production installations severing lots of online XMPP users.

**Comment by cjbottaro** [comment]
Awesome, thank you for the info!
