### ISSUE TITLE
Slow DNS On first request

### ISSUE THREAD

**Issue by zkessin** [esl/fusco#19]
This was found on our system with a LOT Of tracing. when I started a fusco process pool (poolboy) on the first request each fusco process made took about 4.5-5s to do a DNS lookup. We were able to work around this by adding the host in question to the /etc/hosts file. However, it seemed odd that it required so many DNS lookups and that they were so slow. 

This was on OTP 18

(Somewhat processed trace of an offending process)
```
{message,send,<0.411.0>,1579007953265,
         {<0.191.0>,
          {{<0.411.0>,#Ref<0.0.2.1298>},
           {1,1,"some-internal-server.ourcompany.net"}}}}.

% 
{message,function_out,<0.411.0>,1579007953265,
         {{inet_gethost_native,getit,2},2}}.

% 
{message,'receive',<0.411.0>,1579007958217,
         {#Ref<0.0.2.1298>,
          {ok,<<4,0,0,0,1,10,30,30,19,0,0,0,1,108,97,98,45,118,120,108,97,
                98,45,48,49,48,49,48,49,45,49,57,46,118,49,118,48,120,46,
                110,101,116,0>>}}}.


```

**Comment by NelsonVides** [comment]
This seems to me like an issue with the DNS resolver in the given version of OTP, but can't say for sure. I'll close this ticket as it is very old and the OTP version is long unsupported, but if it happens with a newer version please let us know reopening this issue.
