### ISSUE TITLE
An update?

### ISSUE THREAD

**Issue by Neustradamus** [esl/fusco#21]
Dear @esl team, @oscarh, @lastres, @leonardb, @fdmanana, @philwitty, @amanshin, @Euen, @erszcz, @NelsonVides, @dLuna, @RumataEstor, @etrepum, @legoscia, @maxlapshin, @uwiger, @emafr, @kklocek, @tolbrino, @fabiomsouto, @preciz,

It is possible to have an update to have compatibility with latest Erlang/OTP versions?

Thanks in advance.

**Comment by kvakvs** [comment]
That's rude tagging everyone on a long inactive project.
